export const data = [
  {
    id: "1",
    name: "Home",
    pages: [],
    isActive: false,
    menu: [
      {
        id: "2",
        name: "Overview",
        isActive: false,
        path: "/dashboard/overview",
        menu: [],
        pages: [
          {
            id: "3",
            name: "Role Management",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createRole",
              read: "/api/v1/roles/fetchRole,/api/v1/roles/fetchRoleWithUsers,/api/v1/roles/fetchRoleByUser",
              update: "/api/v1/roles/updateRole",
              delete: "/api/v1/roles/deleteRole",
              upload: "",
              download: "",
            },
          },
        ],
      },
      {
        id: "4",
        name: "Orders",
        isActive: false,
        path: "/order",
        menu: [],
        pages: [
          {
            id: "5",
            name: "User Management",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createuser",
              read: "/api/v1/users/fetchuser,/api/v1/users/fetchuserWithUsers,/api/v1/users/fetchuserByUser",
              update: "/api/v1/users/updateuser",
              delete: "/api/v1/users/deleteuser",
              upload: "",
              download: "",
            },
          },
        ],
      },
      {
        id: "6",
        name: "Exception",
        isActive: false,
        path: "/exception",
        menu: [],
        pages: [
          {
            id: "7",
            name: "User Management",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createuser",
              read: "/api/v1/users/fetchuser,/api/v1/users/fetchuserWithUsers,/api/v1/users/fetchuserByUser",
              update: "/api/v1/users/updateuser",
              delete: "/api/v1/users/deleteuser",
              upload: "",
              download: "",
            },
          },
        ],
      },
      {
        id: "8",
        name: "Courier",
        isActive: false,
        path: "/courier",
        menu: [],
        pages: [
          {
            id: "9",
            name: "User Management",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createuser",
              read: "/api/v1/users/fetchuser,/api/v1/users/fetchuserWithUsers,/api/v1/users/fetchuserByUser",
              update: "/api/v1/users/updateuser",
              delete: "/api/v1/users/deleteuser",
              upload: "",
              download: "",
            },
          },
        ],
      },
    ],
    icon: "Menu",
  },
  {
    id: "10",
    name: "Orders",
    pages: [],
    isActive: false,
    menu: [
      {
        id: "11",
        name: "View Orders",
        isActive: false,
        path: "/orders/view-orders",
        menu: [],
        pages: [
          {
            id: "8",
            name: "Overview",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createRole",
              read: "/api/v1/roles/fetchRole,/api/v1/roles/fetchRoleWithUsers,/api/v1/roles/fetchRoleByUser",
              update: "/api/v1/roles/updateRole",
              delete: "/api/v1/roles/deleteRole",
              upload: "",
              download: "",
            },
          },
        ],
      },
      {
        id: "12",
        name: "Add Order",
        isActive: false,
        path: "/orders/add-order/pickup",
        menu: [],
        pages: [
          {
            id: "10",
            name: "Partner List",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createuser",
              read: "/api/v1/users/fetchuser,/api/v1/users/fetchuserWithUsers,/api/v1/users/fetchuserByUser",
              update: "/api/v1/users/updateuser",
              delete: "/api/v1/users/deleteuser",
              upload: "",
              download: "",
            },
          },
        ],
      },
    ],
    icon: "orders",
  },
  {
    id: "14",
    name: "Weight Management",
    pages: [],
    isActive: false,
    menu: [
      {
        id: "20",
        name: "Weight Freeze",
        isActive: false,
        path: "/weight-freeze",
        menu: [],
        pages: [
          {
            id: "21",
            name: "Plan Management",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createRole",
              read: "/api/v1/roles/fetchRole,/api/v1/roles/fetchRoleWithUsers,/api/v1/roles/fetchRoleByUser",
              update: "/api/v1/roles/updateRole",
              delete: "/api/v1/roles/deleteRole",
              upload: "",
              download: "",
            },
          },
        ],
      },
    ],
    icon: "Weight",
  },
  {
    id: "41",
    name: "Catalogues",
    pages: [],
    isActive: false,
    menu: [
      {
        id: "42",
        name: "Catalogue",
        isActive: false,
        path: "/catalogues/catalogue",
        menu: [],
        pages: [
          {
            id: "43",
            name: "Catalogue",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createRole",
              read: "/api/v1/roles/fetchRole,/api/v1/roles/fetchRoleWithUsers,/api/v1/roles/fetchRoleByUser",
              update: "/api/v1/roles/updateRole",
              delete: "/api/v1/roles/deleteRole",
              upload: "",
              download: "",
            },
          },
        ],
      },
      {
        id: "42",
        name: "Channel Integration",
        isActive: false,
        path: "/catalogues/channel-integration",
        menu: [],
        pages: [
          {
            id: "43",
            name: "Courier",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createRole",
              read: "/api/v1/roles/fetchRole,/api/v1/roles/fetchRoleWithUsers,/api/v1/roles/fetchRoleByUser",
              update: "/api/v1/roles/updateRole",
              delete: "/api/v1/roles/deleteRole",
              upload: "",
              download: "",
            },
          },
        ],
      },
    ],
    icon: "Catalogue",
  },
  {
    id: "48",
    name: "Wallet",
    pages: [],
    isActive: false,
    menu: [
      {
        id: "49",
        name: "Recharge Wallet",
        isActive: false,
        path: "/wallet/recharge-wallet",
        menu: [],
        pages: [
          {
            id: "50",
            name: "Client List",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createRole",
              read: "/api/v1/roles/fetchRole,/api/v1/roles/fetchRoleWithUsers,/api/v1/roles/fetchRoleByUser",
              update: "/api/v1/roles/updateRole",
              delete: "/api/v1/roles/deleteRole",
              upload: "",
              download: "",
            },
          },
        ],
      },
      {
        id: "51",
        name: "Transactions",
        isActive: false,
        path: "/wallet/transactions",
        menu: [],
        pages: [
          {
            id: "52",
            name: "Transactions",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createRole",
              read: "/api/v1/roles/fetchRole,/api/v1/roles/fetchRoleWithUsers,/api/v1/roles/fetchRoleByUser",
              update: "/api/v1/roles/updateRole",
              delete: "/api/v1/roles/deleteRole",
              upload: "",
              download: "",
            },
          },
        ],
      },
    ],
    icon: "Wallet",
  },
  {
    id: "49",
    name: "Plans",
    pages: [],
    isActive: false,
    menu: [
      {
        id: "50",
        name: "Plans",
        isActive: false,
        path: "/plans",
        menu: [],
        pages: [
          {
            id: "51",
            name: "Plan List",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createRole",
              read: "/api/v1/roles/fetchRole,/api/v1/roles/fetchRoleWithUsers,/api/v1/roles/fetchRoleByUser",
              update: "/api/v1/roles/updateRole",
              delete: "/api/v1/roles/deleteRole",
              upload: "",
              download: "",
            },
          },
        ],
      },
      {
        id: "50",
        name: "Plan Details",
        isActive: false,
        path: "/plan-details",
        menu: [],
        pages: [
          {
            id: "51",
            name: "Plan List",
            isActive: false,
            permissions: {
              create: true,
              read: true,
              update: true,
              delete: true,
              upload: true,
              download: true,
            },
            routes: {
              create: "/api/v1/roles/createRole",
              read: "/api/v1/roles/fetchRole,/api/v1/roles/fetchRoleWithUsers,/api/v1/roles/fetchRoleByUser",
              update: "/api/v1/roles/updateRole",
              delete: "/api/v1/roles/deleteRole",
              upload: "",
              download: "",
            },
          },
        ],
      },
    ],
    icon: "Plans",
  },
];
