name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - develop
      - master

jobs:
  production:
    runs-on: production
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [20.x]

    env:
      REACT_APP_ENV: ${{ secrets.REACT_APP_ENV }}
      REACT_APP_COMPANY: ${{ secrets.REACT_APP_COMPANY }}
      REACT_APP_SELLER_PROD: ${{ secrets.REACT_APP_SELLER_PROD }}
      REACT_APP_PARTNER_PROD: ${{ secrets.REACT_APP_PARTNER_PROD }}
      REACT_APP_FILE_SERVER_PROD: ${{ secrets.REACT_APP_FILE_SERVER_PROD }}
      REACT_APP_LANDMARK_PROD: ${{ secrets.REACT_APP_LANDMARK_PROD }}
      REACT_APP_TRACKING_URL_PROD: ${{ secrets.REACT_APP_TRACKING_URL_PROD }}
      REACT_APP_SELLER_WEB_URL_PROD: ${{ secrets.REACT_APP_SELLER_WEB_URL_PROD }}
      REACT_APP_GTM_ID: ${{ secrets.REACT_APP_GTM_ID }}
      REACT_APP_GA4_ID: ${{ secrets.REACT_APP_GA4_ID }}
      REACT_APP_AMAZON_APPLICATION_ID: ${{ secrets.REACT_APP_AMAZON_APPLICATION_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setting Up Production Keys
        run: |
          echo "REACT_APP_ENV: $REACT_APP_ENV"
          echo "REACT_APP_COMPANY: $REACT_APP_COMPANY"
          echo "REACT_APP_SELLER_PROD: $REACT_APP_SELLER_PROD"
          echo "REACT_APP_PARTNER_PROD: $REACT_APP_PARTNER_PROD"
          echo "REACT_APP_FILE_SERVER_PROD: $REACT_APP_FILE_SERVER_PROD"
          echo "REACT_APP_LANDMARK_PROD: $REACT_APP_LANDMARK_PROD"
          echo "REACT_APP_TRACKING_URL_PROD: $REACT_APP_TRACKING_URL_PROD"
          echo "REACT_APP_SELLER_WEB_URL_PROD: $REACT_APP_SELLER_WEB_URL_PROD"
          echo "REACT_APP_GTM_ID: $REACT_APP_GTM_ID"
          echo "REACT_APP_GA4_ID: $REACT_APP_GA4_ID"
          echo "REACT_APP_AMAZON_APPLICATION_ID: $REACT_APP_AMAZON_APPLICATION_ID"

      - name: Install and Build for Production
        run: |
          npm install
          CI=false npm run prod-build --if-present

      - name: Start PM2 Process for Production
        run: |
          npm install -g pm2 typescript serve ts-node
          pm2 start process.json

  development:
    runs-on: development
    if: github.ref == 'refs/heads/develop'

    strategy:
      matrix:
        node-version: [20.x]

    env:
      REACT_APP_ENV: ${{ secrets.REACT_APP_ENV }}
      REACT_APP_COMPANY: ${{ secrets.REACT_APP_COMPANY }}
      REACT_APP_SELLER_DEV: ${{ secrets.REACT_APP_SELLER_DEV }}
      REACT_APP_PARTNER_DEV: ${{ secrets.REACT_APP_PARTNER_DEV }}
      REACT_APP_FILE_SERVER_DEV: ${{ secrets.REACT_APP_FILE_SERVER_DEV }}
      REACT_APP_LANDMARK_DEV: ${{ secrets.REACT_APP_LANDMARK_DEV }}
      REACT_APP_TRACKING_URL_DEV: ${{ secrets.REACT_APP_TRACKING_URL_DEV }}
      REACT_APP_SELLER_WEB_URL_DEV: ${{ secrets.REACT_APP_SELLER_WEB_URL_DEV }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setting Up Development Keys
        run: |
          echo "REACT_APP_ENV: $REACT_APP_ENV"
          echo "REACT_APP_COMPANY: $REACT_APP_COMPANY"
          echo "REACT_APP_SELLER_DEV: $REACT_APP_SELLER_DEV"
          echo "REACT_APP_PARTNER_DEV: $REACT_APP_PARTNER_DEV"
          echo "REACT_APP_FILE_SERVER_DEV: $REACT_APP_FILE_SERVER_DEV"
          echo "REACT_APP_LANDMARK_DEV: $REACT_APP_LANDMARK_DEV"
          echo "REACT_APP_TRACKING_URL_DEV: $REACT_APP_TRACKING_URL_DEV"
          echo "REACT_APP_SELLER_WEB_URL_DEV: $REACT_APP_SELLER_WEB_URL_DEV"

      - name: Install and Build for Development
        run: |
          npm install
          CI=false npm run dev-build --if-present

      - name: Start PM2 Process for Development
        run: |
          npm install -g pm2 typescript serve ts-node
          pm2 start process.json
